# Copyright (c) 2022-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# See LICENSE for license information.

# A workflow to trigger TE build on GitHub
name: 'Build'
on:
  pull_request:
  workflow_dispatch:
jobs:
  pytorch:
    name: 'PyTorch'
    runs-on: [ self-hosted, Linux, X64, nvidia, gpu-8 ]
    defaults:
      run:
        shell: bash
    container:
      image: harbor.baai.ac.cn/flagscale/cuda12.8.1-torch2.7.1-python3.10-te2.9:20260209
      options: --user root
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 'Build'
        run:
          source /opt/miniconda3/etc/profile.d/conda.sh
          conda activate flagscale-train
          pip install --no-build-isolation . -v --no-deps
        env:
          NVTE_FRAMEWORK: pytorch
          TE_WITH_NCCL: 1
      - name: 'Sanity check'
        run: 
          source /opt/miniconda3/etc/profile.d/conda.sh
          conda activate flagscale-train
          python3 tests/pytorch/test_sanity_import.py
